title: Jhi Aitken
description: >-
  Co-founder of HardStop. I'm drawn to building things that haven't been done
  before. Right now that means helping adults and kids block the content they
  don't want in their lives, for themselves or for their children. I write
  here mostly for myself, to consolidate my ideas and give my own creativity
  and expression an outlet. If you've stumbled across it and find something of
  value, all the better.
url: "https://jhiaitken.com"
permalink: /:year/:month/:day/:title/
markdown: kramdown
exclude: [README.md]
