title: Jhi Aitken
description: >-
  Co-founder at HardStop. We built the first solution that truly blocks
  pornography for individuals and children.
url: "https://jhiaitken.com"
permalink: /:year/:month/:day/:title/
markdown: kramdown
exclude: [README.md]
